app/urls.py
from django.urls import path
from .views import index, HomeView

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('home/', HomeView.as_view(), name='home')
]

bank_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from .views import index, LoginView, RegisterView, logout

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout, name='logout')
]

app/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from datetime import datetime, timedelta
from re import compile as re_compile


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        '''Create and saves a new user'''
        if not email:
            raise ValueError('User must have an email address')
        if not password:
            raise ValueError('User needs a password')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def validate_register(self, postData):
        errors = {}
        EMAIL_REGEX = re_compile(
            r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.+_-]+.[a-zA-Z]+$'
        )

        # Email validation
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = 'Invalid email address'
        elif len(self.filter(email=postData['email'])) > 0:
            errors['email'] = 'User with that email already exists'

        # First and last naame validations
        if len(postData['first_name']) < 4:
            errors['first_name'] = 'First name must be 4 or more characters'
        elif len(postData['first_name']) > 45:
            errors['first_name'] = 'First name must be 45 or less characters'
        if len(postData['last_name']) < 4:
            errors['last_name'] = 'Last name must be 4 or more characters'
        elif len(postData['first_name']) > 45:
            errors['last_name'] = 'Last name must be 45 or less characters'

        # Birthdate validation
        todaysDate = datetime.now().date()
        if todaysDate < postData['birthday']:
            errors['birthday'] = 'Birthday must be in the past'
        elif todaysDate - postData['birthday'] < timedelta(days=365*18):
            errors['birthday'] = 'Must be 18 years old to create an account'

        # Password validations
        if len(postData['password']) < 8:
            errors['password'] = 'Password must be 8 opr more characters'
        elif(postData['password'] != postData['password_confirm']):
            errors['password'] = 'Passwords must match'

        return errors


class User(AbstractBaseUser):
    '''Custom user model supporting using email instead of username'''
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    birthday = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

app/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import View
from django.core.exceptions import ImproperlyConfigured
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    return redirect(reverse('app:home'))


class Main(object):
    template = None

    def get_template(self):
        if self.template is not None:
            return self.template
        raise ImproperlyConfigured('Template not defined.')


class HomeView(LoginRequiredMixin, Main, View):
    login_url = '/users/login/'
    template = 'index.html'

    def get(self, request):
        return render(request, self.get_template())

    def post(self, request):
        return redirect(reverse('app:home'))

users/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import View
from django.core.exceptions import ImproperlyConfigured
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout as logout_user
from django.contrib.auth import get_user_model


def index(request):
    return redirect(reverse('users:login'))


class Main(object):
    template = None

    def get(self, request):
        return render(request, self.get_template())

    def get_template(self):
        if self.template is not None:
            return self.template
        raise ImproperlyConfigured('Template not defined.')


class LoginView(Main, View):
    template = 'login.html'

    def post(self, request):
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user is not None:
            login(request, user)
            return redirect(reverse('app:index'))
        messages.error(request, 'Invalid credentials')
        return redirect(reverse('users:login'))


class RegisterView(Main, View):
    template = 'register.html'

    def post(self, request):
        errors = get_user_model().objects.validate_register(request.POST)
        if len(errors) > 0:
            for key, error in errors.items():
                messages.error(request, error)
            return redirect(reverse('users:register'))

        user = get_user_model().objects.create_user(
            email=request.POST['email'],
            password=request.POST['password1'],
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            birthday=request.POST['birthday']
        )
        login(request, user)
        return redirect('app:index')


def logout(request):
    logout_user(request)
    return redirect(reverse('users:login'))

app/templates/index.html
<!--
  Author: Justin Clayton
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Title</title>
  {% load static %}
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
  <header>
    <h1>App Name</h1>
    <div id="status">
      <p>Welcome, {{ request.user.get_full_name }}</p>
      <a class="btn btn-warning" href="{% url 'users:logout' %}">Logout</a>
    </div>
  </header>
  <main class="container bg-light text-center">
    <div class="row">
      <h1>Hi</h1>
    </div>
  </main>
</body>
</html>

users/templates/login.html
<!--
  Author: Justin Clayton
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login | Monolith Bank</title>
  <!-- {% load static %} -->
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../static/css/login_reg.css">
  <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/users.css' %}"> -->
</head>

<body>
  <div id="container">
    <img src="../static/img/logo.png" alt="">
    
    <div id="login_form">
      <p>Please sign in with your email and password:</p>
      <form action="" method="post">
        <fieldset>
          <input type="text" name="email" id="email" placeholder="Email Address">
        </fieldset>
        <fieldset>
          <input type="text" name="password" id="password" placeholder="Password">
        </fieldset>
        <fieldset>
          <input type="submit" value="Login">
        </fieldset>
      </form>
      
      
    </div>
    <a href="">Not a member? Create an account</a>

  </div>
</body>
</html>

users/templates/register.html
<!--
  Author: Justin Clayton
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Register | Monolith Bank</title>
  <!-- {% load static %} -->
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
    crossorigin="anonymous">
  <link rel="stylesheet" href="../static/css/login_reg.css">
  <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/users.css' %}"> -->
</head>

<body>
  <div id="container">
    <img src="../static/img/logo.png" alt="">
    
    <div id="login_form">
      <form action="" method="post">
        <fieldset>
          <input type="text" name="first_name" id="first_name" placeholder="First Name">
        </fieldset>
        <fieldset>
          <input type="text" name="last_name" id="last_name" placeholder="Last Name">
        </fieldset>
        <fieldset>
          <label for="dob">Date of Birth: </label>
          <input type="date" name="dob" id="dob">
        </fieldset>
        <fieldset>
          <input type="text" name="email" id="email" placeholder="Email Address">
        </fieldset>
        <fieldset>
          <input type="text" name="password" id="password" placeholder="Password">
        </fieldset>
        <fieldset>
          <input type="text" name="confirm_password" id="confirm_password" placeholder="Confirm Password">
        </fieldset>
        <fieldset>
          <input type="submit" value="Register">
        </fieldset>
      </form>
      
      
    </div>

  </div>
</body>
</html>